replicaCount: 1
fullnameOverride: mm-kafka

service:
  type: ClusterIP
  port: 9092

persistence:
  enabled: true
  size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 1
