controller:
  replicaCount: 1

broker:
  replicaCount: 0

service:
  type: ClusterIP
  port: 9092

persistence:
  enabled: true
  size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 1500m

overrideConfiguration:
  "listeners": "CLIENT://:9092,CONTROLLER://:9093"
  "advertised.listeners": "CLIENT://mm-kafka-controller-headless:9092"
  "listener.security.protocol.map": "CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  "inter.broker.listener.name": "CLIENT"
