receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 # standard port inside the container
      http:
        endpoint: 0.0.0.0:4318 # standard port inside the container

exporters:
  zipkin:
    endpoint: ${MOVIE_MATE_OTEL_ZIPKIN_ENDPOINT}
  prometheus:
    endpoint: ${MOVIE_MATE_OTEL_PROMETHEUS_ENDPOINT}

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

