fullnameOverride: mm-prometheus

server:
  service:
    name: mm-prometheus
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m


# 👇 ADD PORT!
extraScrapeConfigs: |
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['mm-otel-collector:PORT']

alertmanager:
  enabled: false