# Save this as redpanda-console.yaml
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  namespace: movie-mate
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: redpanda-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: movie-mate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: docker.redpanda.com/redpandadata/console:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "mm-kafka:9092"
