fullnameOverride: mm-redis
nameOverride: mm-redis

auth:
  enabled: false    # Set to true for production!

architecture: standalone

master:
  persistence:
    enabled: true
    size: 1Gi

resources:
  requests:
    memory: 64Mi
    cpu: 200m
  limits:
    memory: 256Mi
    cpu: 500m
