# Default values.yaml for mm-user-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

image:
  repository: manki1337/mm-discovery-server
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port:
  targetPortName:


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 384Mi

containerPort:


env:
  # Servlet
  - name: BOOTSTRAP_EXPECT
    value:
  - name: CONSUL_NODE_NAME
    value:
  - name:  CONSUL_DATACENTER
    value:

