fullnameOverride: mm-otel-collector

mode: deployment

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    protocol: TCP
  zipkin:
    enabled: true
    containerPort: 9411
    servicePort: 9411
    protocol: TCP

image:
  repository: otel/opentelemetry-collector
  tag: "0.132.0"

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
    zipkin: {}

  exporters:
    debug:
      verbosity: detailed
    prometheus:
      endpoint: "0.0.0.0:8888"
    zipkin:
      endpoint: ""

  service:
    telemetry:
      metrics:
        address: "0.0.0.0:9999"
    pipelines:
      traces:
        receivers: [otlp, zipkin]
        exporters: [debug, zipkin]
      metrics:
        receivers: [otlp]
        exporters: [debug, prometheus]

resources:
  requests:
    memory: 128Mi
    cpu: 400m
  limits:
    memory: 512Mi
    cpu: 800m
