fullnameOverride: mm-grafana

adminUser: admin
adminPassword: changeme

service:
  type: ClusterIP
  port:

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 300m

persistence:
  enabled: true
  storageClassName: local-path
  size: 2Gi
