name: Deploy Trigger

on:
  repository_dispatch:
    types: [ user-service-builded, recommendation-service-builded ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Aggregation Repository
        uses: actions/checkout@v2

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Service via SSH
        run: |
          SERVICE="${{ github.event.client_payload.service }}"
          IMAGE_TAG="${{ github.event.client_payload.tag }}"
          echo "Deploying service: $SERVICE with tag: $IMAGE_TAG"
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Call a generic deploy script that handles multiple services
          /path/to/deploy.sh "$SERVICE" "$IMAGE_TAG"
          EOF