name: Common Docker Hub config

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  set-config:
    runs-on: ubuntu-latest
    outputs:
      dockerUser: ${{ steps.get.outputs.dockerUser }}
      dockerPassword: ${{ steps.get.outputs.dockerPassword }}
    steps:
      - id: get
        run: |
          echo "Using Docker Hub user: ${{ secrets.DOCKERHUB_USER }}"
          echo "dockerUser=${{ secrets.DOCKERHUB_USER }}" >> $GITHUB_OUTPUT
          echo "dockerPassword=${{ secrets.DOCKERHUB_PASSWORD }}" >> $GITHUB_OUTPUT