name: Common Docker Hub config

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: false
      DOCKERHUB_PASSWORD:
        required: false

jobs:
  set-config:
    runs-on: ubuntu-latest
    outputs:
      dockerUser: ${{ steps.get.outputs.dockerUser }}
      dockerPassword: ${{ steps.get.outputs.dockerPassword }}
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
    steps:
      - id: get
        run: |
          echo ${{ secrets.DOCKERHUB_USER }} | sed 's/./& /g'
          echo "Env DOCKERHUB_USER: $DOCKERHUB_USER"
          echo "dockerUser=${{ secrets.DOCKERHUB_USER }}" >> $GITHUB_OUTPUT
          echo "dockerPassword=${{ secrets.DOCKERHUB_PASSWORD }}" >> $GITHUB_OUTPUT